= Development

Start the API Server, or jack-in with your favorite editor.

----
$ clj -Adev
----

On the first startup, there will be a number of repos cloned, which may take up to a few minutes.

Wait for the Clojure prompt:

----
Clojure 1.10.1
user=>
----

Type `(start)`

----
user=> (start)
----


----
Starting Crux node
[Edge] Now make code changes, then enter (reset) here
:initiated
----

If this is your first time running Site, you'll need to initialize your database.
Follow the setup instructions in the REPL to setup an API, authentication resources, superuser role, and superuser.

NOTE If at any point you need to restart from the beginning, simply delete the `log` and `db` folders.

----
rm -rf log db
----

Some frontend apps need access to site's CLI in order to deploy their resources.

In order to get the CLI up and running, start by adding `bin/site` to your PATH.

If you did the previous setup correctly, you should be able to get a token from the webserver.

----
$ site get-token -u SUPER_USER_NAME -p SUPER_USER_PASSWORD
site: Unix pass prefix: site/localhost/
site: Get token from http://localhost:2021/_site/token
site: Access token acquired for SUPER_USER_NAME: XXXXXXXXXXXXXXXXXXXXXXX
site: Token expires in 3600 seconds
site: Storing token in ~/.local/share/site/access-token.json
----
