= Site

Site is a project from https://juxt.pro[JUXT] to build a Resource Server out of
our open-source https://opencrux.com[Crux] database.

Site supports web content, and https://www.openapis.org/[OpenAPI]. You can use
Site as a versioned
https://en.wikipedia.org/wiki/Content_management_system[Content Management
System].

== What is Site?

Site is a Resource Server, built on the Crux database.

You can put things into Site with (HTTP) PUT requests. When you do this, Site
will put (the representation of) your thing (document, image, video, data…) into
the database. You can get these later with a (HTTP) GET request with the same
URI. In this way, Site behaves like a web server, with an immutable bitemporal
content store.

=== APIs

If you PUT a JSON document with a `Content-Type` of
`application/vnd.oai.openapi+json;version=3.0.2`, Site will treat this as an
https://www.openapis.org/[OpenAPI] API definition, and serve that API for
you. This OpenAPI API definition will contain the API endpoints, and provide
schemas for the data transferred by the API. This tells the server how to
validate data coming in to the API, and how to construct data on the way out.

APIs served from Site are good web citizens. They implement HTTP method
semantics properly, with support for content negotiation, conditional requests,
range requests and authentication.

APIs are also able to benefit from Site's authorization module, Pass, providing
Policy-Based Access Control, loosely based on XACML.

== Test drive

=== Requirements

Before you start, you'll need to have the following installed:

* Java 9+ (Site is not compatible with Java 8 and below!)
* https://clojure.org/guides/getting_started[Clojure] and
* https://github.com/babashka/babashka[Babashka] installed on your system.

=== Clone this repo

----
$ git clone https://github.com/juxt/site
----

=== Configure

There's a sample configuration in `etc` you should copy to `$HOME/.config/site/config.edn`.

----
$ mkdir -p $HOME/.config/site
$ cp site/etc/config.edn $HOME/.config/site/config.edn
----

=== Configure a password

[TIP]
--
If you have `pass` installed, this is a good time to configure a password for
your superuser. We'll assume the superuser will be named `admin`, but feel free
to choose your own username here.

----
$ pass generate site/local/admin
----
--

=== Start the server

Start the Site server:

----
$ site/bin/site-server
----


=== Bootstrap

Bootstrap the new system by adding the minimum resources that are required to allow remote access.

We'll be using ncat (`ncat`), but you can replace `ncat` with `telnet`, or `ncat`, depending on what's available for your system.

[NOTE]
--
Arch users can install `ncat` by installing the `nmap` package:

----
$ sudo pacman -Sy nmap
----
--

REPL-in to the server

TIP: Prefix the command with `rlwrap` if you have it installed.

----
$ ncat localhost 50505

Site by JUXT. Copyright (c) 2021, JUXT LTD.
Type :repl/quit to exit

[ ]  Site API not installed.  Enter (put-site-api!) to fix this.
[ ]  Authentication resources not installed.  Enter (put-auth-resources!) to fix this.
[ ]  Role of superuser not yet created. Enter (put-superuser-role!) to fix this.
[ ]  No superusers exist. Enter (put-superuser! <username> <fullname>)
     or (put-superuser! <username> <fullname> <password>) to fix this.
site>
----

Install the Site API:

----
site> (put-site-api!)
----

Install the authentication rules:

----
site> (put-auth-resources!)
----

Install the superuser role:

----
site> (put-superuser-role!)
----

Finally, create a superuser.

----
site> (put-superuser! "admin" "Administrator")
----

Replace `"admin"` and `"Administrator"` with your own username and full name.

NOTE: We recommend that you generate a password with `pass`, but if you haven't
done so, you can add a password as a final argument to `put-superuser!`.

Quit the REPL, for example, with `Ctrl-C` or by typing `:repl/quit`.

=== Run the site tool

The site tool is a command-line utility that allows you to remotely administer site.

We must first get a token that we can use for API access. This process authenticates to the site server using your password.

.Here, replace `admin` with your username (or let it default to your OS username)
----
$ site/bin/site get-token -u admin
----

Now we can use the site tool for remote administration. Try the following:

----
$ site/bin/site list-users
----

== License

The MIT License (MIT)

Copyright © 2020-2021 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
