= Site (2.0)

Site is a standards-compliant web server, fulfilling the roles of an https://www.rfc-editor.org/rfc/rfc6749[OAuth2] resource server and authorization server.

[quote,https://www.rfc-editor.org/rfc/rfc6749#section-1.1]
--
resource server:: The server hosting the protected resources, capable of accepting and responding to protected resource requests using access tokens.
--

Resources are documents which represent a resource's identity (URI), configuration and current state (which might be some data, image or other media).
Site stores resources in a database.

A resource request is a standard web request to a URI (as part of an API, such as https://www.openapis.org/[OpenAPI]) or https://graphql.org/[GraphQL] request.

Requests contain an access-token, acquired from an authorization server:

[quote,https://www.rfc-editor.org/rfc/rfc6749#section-1.1]
--
authorization server:: The server issuing access tokens to the client
after successfully authenticating the resource owner and obtaining
authorization.
--

Currently, the only supported database is JUXT's immutable https://xtdb.com[XTDB] database.
XTDB is a good fit for Site, since many of its features (such as document ids and references) map cleanly onto web concepts (such as URIs and links).

== Features

=== Resource Server

* Content Negotiation
* Conditional Requests
* GraphQL

=== Authorization Server

* Client Registration
* User Authentication (Basic, Login form, OpenID)
* OAuth2 access token grants

== Status

The previous 1.0 generation of Site is maintained at https://github.com/juxt/site.

This 2.0 generation is in development. Please do not use until further notice.

== Consulting

Contact info@juxt.pro if you would like help, we can provide professional consulting services for Site and/or XTDB.

== License

The MIT License (MIT)

Copyright © 2020-2023 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
