= Site

image:https://circleci.com/gh/juxt/site/tree/master.svg?style=svg["CircleCI", link="https://circleci.com/gh/juxt/site/tree/master"]

Site is a project from https://juxt.pro[JUXT] to build an OAuth2 Resource Server
around our open-source https://xtdb.com[XTDB] database.

Site supports web content, https://www.openapis.org/[OpenAPI] and GraphQL. You
can use Site as a versioned
https://en.wikipedia.org/wiki/Content_management_system[Content Management
System].

An official (work in progress) documentation website can be found
https://juxtsite.netlify.app/[here].

== What is Site?

Site is a Resource Server, built on JUXT's https://xtdb.com[XTDB] database.

You can put things into Site with (HTTP) PUT requests. When you do this, Site
will put (the representation of) your thing (document, image, video, data…) into
the database. You can get these later with a (HTTP) GET request with the same
URI. In this way, Site behaves like a web server, with an immutable bitemporal
content store.

=== APIs

If you PUT a JSON document with a `Content-Type` of
`application/vnd.oai.openapi+json;version=3.0.2`, Site will treat this as an
https://www.openapis.org/[OpenAPI] API definition, and serve that API for
you. This OpenAPI API definition will contain the API endpoints, and provide
schemas for the data transferred by the API. This tells the server how to
validate data coming in to the API, and how to construct data on the way out.

APIs served from Site are good web citizens. They implement HTTP method
semantics properly, with support for content negotiation, conditional requests,
range requests and authentication.

APIs are also able to benefit from Site's authorization module, Pass, providing
Policy-Based Access Control.

== Installation

Follow the link:InstallationGuide.adoc[installation guide].

== Status

Site is deployed in production on a number of JUXT client projects but future
versions are still in the development stages.

You should expect Site's current design and APIs to change and be prepared to
make changes to any system that uses Site.

Contact info@juxt.pro if you would like help, we can provide professional
consulting services for Site and XTDB.

== Configuration

For testing:

`~/.config/site/openid-client.edn`

[source,clojure]
----
{:juxt.pass.alpha/issuer "https://juxt.eu.auth0.com"
 :juxt.pass.alpha/client-id "d8X0TfEIcTl5oaltA4oy9ToEPdn5nFUK"
 :juxt.pass.alpha/client-secret "XXXX"
 :juxt.pass.alpha/redirect-uri "https://site.test/openid/callback"}
----

== License

The MIT License (MIT)

Copyright © 2020-2021 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
