= Applications
:toc: left

[NOTE]
--
In OAuth, Applications are created and authorized by an authorization
server. The actions described in this chapter could be part of another Site
instance which carries out the duties of an OAuth Authorization Server.

[quote,https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-05#section-1.3.3]
____
The authorization server
may be the same server as the resource server…
____

Should we consider having a different hostname for entities managed by the
Authorization Server, e.g. `auth.site.test` ?
--


== Create the action to create an application

.Creating the action
[[example-create-action-put-application]]
====
[source,clojure]
----
include::../../test/juxt/demo.clj[tag=create-action-put-application!,indent=0]
----
====

== Grant permission to create an application

.Granting permission
[[example-grant-permission-put-application]]
====
[source,clojure]
----
include::../../test/juxt/demo.clj[tag=grant-permission-to-invoke-action-put-application!,indent=0]
----
====

== Create the action to authorize an application

====
[source,clojure]
----
include::../../test/juxt/demo.clj[tag=create-action-authorize-application!,indent=0]
----
====

== Grant permission to authorize an application

====
[source,clojure]
----
include::../../test/juxt/demo.clj[tag=grant-permission-to-invoke-action-authorize-application!,indent=0]
----
====

== Create the action to issue an access token

====
[source,clojure]
----
include::../../test/juxt/demo.clj[tag=create-action-issue-access-token!,indent=0]
----
====

== Grant permission to issue an access token

====
[source,clojure]
----
include::../../test/juxt/demo.clj[tag=grant-permission-to-invoke-action-issue-access-token!,indent=0]
----

<1> All users are permitted to issue access tokens to applications that have
authorized to access resources on their behalf.

====
