= The Authorization Server
:toc: left

== Introduction

(((Authorization Server)))
(((OAuth2)))

In OAuth, an Authorization Server is responsible for "issuing access tokens to
the client after successfully authenticating the resource owner and obtaining
authorization."

[quote,RFC 6749,https://datatracker.ietf.org/doc/html/rfc6749#section-1.1]
--
The interaction between the authorization server and resource server
is beyond the scope of this specification.  The authorization server
may be the same server as the resource server or a separate entity.
--

Since the relationship between the authorization server and resource server in
OAuth2 is undefined, Site is able to fulfill the role of an authorization server
as well as a resource server.

== Configuring the Authorization Server

TODO: Do a put of an authorization server with a get-fn

NOTE: TODO: If this is written as an action, much of it can be defaulted leaving
the user to decide the URI and other optional details, perhaps such as which
types of authorization grant to support.

[source,clojure]
----
include::../../test/juxt/book.clj[tag=install-authorization-server!,indent=0]
----

NOTE: TODO
