= Basic Authentication
:toc: left

== Introdution

Basic HTTP Authentication is defined in
https://www.rfc-editor.org/rfc/rfc7617.html[RFC 7617].

[quote,RFC 7617,https://www.rfc-editor.org/rfc/rfc7617.html]
--
The Basic authentication scheme is based on the model that the client
needs to authenticate itself with a user-id and a password for each
protection space ("realm").  The realm value is a free-form string
that can only be compared for equality with other realms on that
server.  The server will service the request only if it can validate
the user-id and password for the protection space applying to the
requested resource.
--

Although Basic HTTP Authentication is rarely used nowadays, it is useful to
understand as it brings together concepts of User, User Identity, Action,
Permission and Protection Space.

These will be involved in the securing of APIs using HTTP Bearer Authentication
in a later chapter.

== Exploring Basic Auth

For the rest of this chapter we'll explore Basic Authentication by setting up
the following resources:

. A document at `+https://site.test/protected-by-basic-auth/document.html+`
which requires the User can perform the Action
`+https://site.test/actions/get-protected-resource+`. We'll called this the
_protected document_. This is explained in <<basic-create-protected-resource>>.

. A Permission to allow Alice to access this protected document. This is added
in <<basic-permit-user>>.

. A Protection Space that requires HTTP Basic Authentication. This is done in
<<basic-establish-protection-space>>.

. A User Identity for Alice, including a username/password pair, that Alice can use
to authenticate. This is added in <<basic-add-user-identity>>.

<<basic-auth-flow>> shows the interaction between the components.

.How HTTP 'Basic' Authentication works in Site
[[basic-auth-flow]]
[plantuml,basic-auth-flow,svg]
....
skinparam monochrome true
autonumber

actor Alice as user
participant browser
participant "/protected-by-basic-auth/document.html" as document
participant Pass as pass
database XTDB

browser -> document: GET
document <- XTDB: Lookup protection spaces\n(one is found for 'Basic' auth)
document -> pass: Check permission to perform\nhttps://site.test/actions/get-protected-resource
document <- pass: Denied
browser <- document: 401 Unauthorized\nwith WWW-Authenticate header\nincluding realm value 'Wonderland'

user <- browser: "Please login to Wonderland"
user -> browser: Enters 'alice' and 'garden'
browser -> document: GET with Authorization header\nwith base64 encoded username/password pair
document <- XTDB: Lookup protection spaces\n(one is found for 'Basic' auth)
document -> pass: Match credentials
pass <- XTDB: User Identity found
pass -> XTDB: Create new Subject
document <- pass: 'Alice' set as the Subject
document -> pass: Check permission to perform\nhttps://site.test/actions/get-protected-resource
document <- pass: Allowed
browser <- document: 200 OK
....

////

Note that the 'Pass' sub-system of Site is responsible for ensuring a Subject
exists in the database so that authorization can work purely against the databse
using Datalog rules.

////

[[basic-create-protected-resource]]
== Create the protected resource

.Creating the protected resource
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=create-resource-protected-by-basic-auth!,indent=0]
----
====

[[basic-permit-user]]
== Permit Alice to access the protected resource

.Permitting Alice to access the protected resource
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=grant-permission-to-resource-protected-by-basic-auth!,indent=0]
----
====

[[basic-establish-protection-space]]
== Establish the Protection Space

.Creating the protected resource
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=put-basic-protection-space!,indent=0]
----
====

[[basic-add-user-identity]]
== Setting Alice's password

To login via Basic Authentication, Alice needs a password. We'll set her a
password of `garden`.

<<ex-put-basic-auth-user-identity>> demonstrates how we can call the Action we
created in <<ex-create-action-put-user-identity>> to give Alice an extra
identity.

[[ex-put-basic-auth-user-identity]]
.Adding a password for Alice
====
Add a User Identity for Alice:

[source,clojure]
----
include::../../test/juxt/book.clj[tag=put-basic-auth-user-identity!,indent=0]
----
====

== Testing

.Failing to provide valid credentials
====
First test without providing credentials:

----
curl -i https://site.test/protected-by-basic-auth/document.html
----

This should return a `401 Unauthorized` response similar to this:

----
HTTP/1.1 401 Unauthorized
Server: nginx/1.20.2
Date: Thu, 26 May 2022 09:34:20 GMT
Content-Type: text/plain;charset=utf-8
Content-Length: 14
Connection: keep-alive
WWW-Authenticate: Basic realm=Wonderland
site-request-id: https://site.test/_site/requests/ea86d312c56eeba257f4b817
permissions-policy: interest-cohort=()

Unauthorized
----
====

.Providing valid credentials
====
Now add the credentials:

----
curl -i https://site.test/protected-by-basic-auth/document.html -u alice:garden
----

This should return a `200 OK` response similar to this:

----
HTTP/1.1 200 OK
Server: nginx/1.20.2
Date: Thu, 26 May 2022 09:34:41 GMT
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
site-request-id: https://site.test/_site/requests/df6b1ce54223971978873604
permissions-policy: interest-cohort=()

<p>This is a protected message that those authorized are allowed to read.</p>
----
====


TIP: Try providing an invalid password. What do you get back?

TIP: Try accessing `https://site.test/protected-by-basic-auth/document.html` in a browser. What happens?
