= Basic Authentication
:toc: left

[NOTE]
--
In this chapter we'll show how to use Basic Authentication to authenticate the initial user.

This will involve adding an Identity with a (hashed) password, a Basic Auth indicator and a 'realm' attribute.

The protected resource will also be given a matching 'realm' attribute and some
other attribute that indicates/triggers Basic Auth

When the 401 response is generated by `handler.clj`, the `WWW-Authenticate`
header will be returned in the response as indicated by the targeted resource,
with the realm attribute being relayed.

The user-agent will return the `Authorization: Basic <user:pass>` header which
will be processed by the middleware, matched to the Identity, and a Subject will
be established in the database. No Session document will be required, since the
Subject representing the login with Basic Auth will be looked up on each request
containing the `Authorization: Basic <user:pass>` header.

The point of covering Basic Auth here is simply a fast way of demonstrating
remote access to the protected resource, which proves that the actions are
working.

The Basic Auth 'Identity' can be simply deleted once an alternative
authentication scheme is in place, such as OpenID.

--

== Setting up a password

To login via Basic Authentication, Alice needs a password.

<<ex-put-basic-auth-user-identity>> demonstrates how we can call the Action we created in <<ex-create-action-put-user-identity>> to give Alice an extra identity.

[[ex-put-basic-auth-user-identity]]
.Adding a password for Alice
====
Add a password for Alice:

[source,clojure]
----
include::../../test/juxt/book.clj[tag=put-basic-auth-user-identity!,indent=0]
----
====
