= Concepts
:step:

This chapter should give you a basic understanding of the key concepts in Site.

You should read this chapter to gain an overview before diving into the details
and practical examples in subsequent chapters.

== Documents

// (((XTDB)))
Data in Site is stored as documents in the https://xtdb.com[XTDB] database.

A **document** is a set of named values.

Values can be strings, numbers, sets, collections, or nested documents, recursively.

Names are 'keywords', which identifiers prefixed with a colon (:).

An example document is shown in <<ex-cat-document>>.

[[ex-cat-document]]
.A document representing a cat
[example]
--
[source,clojure]
----
{:petshop/name "Arya"
 :petshop/species "Cat"
 :petshop/color "black"
 :petshop/favorite-activity "playing with string"}
----
--

All documents in Site can contain any number of additional attributes.

Keyword namespaces are used to protected data from being overwritten when documents are merged together.

Attributes with namespaces of `juxt.site`, `juxt.pass`, `juxt.http`, `xtdb.api` and `xt` are reserved.

== Entities

Each document has the special attribute `:xt/id` which identifies the **entity** to which the document belongs.

The document is a _version_ of the **entity**. There can be just one version of a document for an entity at any one time.

The example given in <<ex-cat-entity>> shows two documents representing the same entity, but at different times.

[[ex-cat-entity]]
.A cat can change
[example]
--
A cat might be represented by the following document:

[source,clojure]
----
{:xt/id "https://example.org/cats/arya"
 :petshop/name "Arya"
 :petshop/species "cat"
 :petshop/color "black"
 :petshop/favorite-activity "playing with string"}
----

But, at a later date, the document might be updated:

[source,clojure]
----
{:xt/id "https://example.org/cats/arya"
 :petshop/name "Arya"
 :petshop/species "cat"
 :petshop/color "black"
 :petshop/favorite-activity "hunting mice"}
----
--

TIP: For more information about documents and entities, visit https://xtdb.com.

== Actions

Actions govern who can read and write documents.

Action are _domain-specific_.
You will need to define your own actions to represent the activities you want to perform on your system.

Here are some example actions:

- Login
- List all products
- Edit a product
- Add a customer
- Promote an employee
- Post an article
- Logout

Actions are themselves defined as documents.

An action document contains one or more *rules*, written in *Datalog* syntax.

A **rule** is written in terms of:

- what is known about the person or machine requesting access (the **subject**)
- what is known about the document being accessed (the **resource**)
- an explicit document that permits access to the action (the **permission**)

For example, it might be that a person's access might depend upon a role they have been assigned, and the document classification of the Resource.
Or that 'VIP' customers may access 'exclusive' special offers.

If a rule is satisfied, access to a document is granted.

When an action grants the creation, modification or deletion of documents, it will also have a program that _performs_ the action.
This program might carry out validation of any inputs and return operations or effects which are applied.

Such a program runs as a *transaction function* in XTDB, which gives certain consistency guarentees.

Site provides a built-in stack-based language which is specially designed for writing these programs.

<<ex-concept-action>> shows a sketch of an action document.

[[ex-concept-action]]
.An example action
[example]
--
[source,clojure]
----
include::../../test/juxt/book.clj[tag=example-action,indent=0]
----
<1> This document is an action.
<2> Rules that govern whether this action can be used to access a document.
<3> A program which creates any effects resulting from performing the action.
--

////
Sometimes a resource is are hierarchical collections of other resources,  to an *action* (or, to be precise, actions), whether the action is a query or a modification.
Some resources are a composition of other resources. For example, a resource might represent a list of produces
////


////
Possibly demote this into the relevant chapter

=== Permissions

For access to be granted to a Resource, a Permission document must exist in the database.

When Rules are evaluated, these Permission documents are returned.
A Permission document represents the granting of access, whether to a specific user explicitly, or to set of users assigned a particular role, or some other relationship.

A Permission document is easily deleted, and so revoking access it as straight-forward as granting access.

Permission documents provide a permanent record of who had access to what, and when.

Rules & Permissions are described more fully in <<ch-rules-and-permissions>>.

A more detailed explanation of actions, rules and permissions can be found in <<ch-actions>>.
////

== Users

An individual that have access to Site is called a **user**.

Each user is defined in a document.

(Since every system has its own requirements about what data must be captured to represent a user, Site doesn't prescribe the data model.)

A user is identified by separate document, called a **user identity**.

Site can tell when a particular user is logging in by matching the user's login credentials with an identity document that relates to the user.

A user may have multiple identities.

When a user successfully logs in, a new entity is created to represent the subject.
The subject document references the user identity (which, in turn, references the user), using attributes that are recognised by Site.
Additionally, the document captures certain details including security attributes of the login.

////
good but perhaps could be demoted to another chapter

Thus, the Subject can be considered a _sub-graph_ of everything we know about
the User logging in.

.The Subject's view
[[cat-model]]
[example]
--
[plantuml,cat,svg]
....
skinparam monochrome true
@startjson
include::cat.json[]
@endjson
....
--
////

Users, user identities and subjects are described in <<ch-users>>.

== Resources

Site maps the XTDB entity onto the concept of a web resource, as defined in REST.

We can understand why XTDB entities make for good web resources, by reading the following quote cite:[rest], replacing the term 'entity' for 'XTDB document'.

[quote,Roy Fielding]
--
The key abstraction of information in REST is a resource. Any information that
can be named can be a resource: a document or image, a temporal service
(e.g. "today's weather in Los Angeles"), a collection of other resources, a
non-virtual object (e.g. a person), and so on. In other words, any concept that
might be the target of an author's hypertext reference must fit within the
definition of a resource. A resource is a conceptual mapping to a set of
entities, not the entity that corresponds to the mapping at any particular point
in time.

More precisely, a resource R is a temporally varying membership function
M~R~(t), which for time t maps to a set of entities, or values, which are
equivalent. The values in the set may be resource representations and/or
resource identifiers.
--

The mapping from an XTDB entity to a web resource is accomplished by the following:

* Each XTDB entity's `:xt/id` attribute is set to a URL (string), identifying the resource.
* Representations are documents, encoding representation metadata in attributes.

<<ex-cat-resource>> shows a document that, currently, has a single HTML representation.

[[ex-cat-resource]]
.A cat can be browsed
[example]
--
[source,clojure]
----
{:xt/id "https://example.org/cats/arya"
 :juxt.http.alpha/content-type "text/html;charset=utf-8" <1>
 :petshop/name "Arya"
 :petshop/species "cat"
 :petshop/color "black"
 :petshop/favorite-activity "playing with string"}
----
<1> This attribute declares that the resource is representable as HTML.
--

Site implements many aspects of the HTTP standards, such as *content-negotiation* and *conditional requests*.

Resources are covered in depth in <<ch-resources>>.

// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// End:
