= Concepts
:step:

This chapter should give you a basic understanding of the key concepts in Site.

You should read this chapter to gain an overview before diving into the details
and practical examples in subsequent chapters.

== Documents

Site stores data in the form of documents.

(((document, definition)))
(((attributes, definition)))
A *document* is a set of named values called *attributes*.
An example document is shown in <<ex-cat-document>>.

[[ex-cat-document]]
.A document representing a cat.
[example]
--
[source,clojure]
----
{:petshop/name "Arya"
 :petshop/species "Cat"
 :petshop/color "black"
 :petshop/favorite-activity "playing with string"}
----
--

(((keywords)))
Names are *keywords*, which are identifiers prefixed with a colon (:).

Values can be strings, numbers, sets, collections, or nested documents.

Since nesting is recursive, a document might be a large hierarchical structure but are typically fairly small.

Site itself is independent of the domain or business context it is part of.
It is these documents that represent the domain.

A document can contain any number of attributes.
Some of these attributes are recognised by Site, and these are documented in this book.
But the rest of the attributes are entirely up to you.

Keyword namespaces are used to keep the attributes that Site recognised from conflicting with attributes that represent the domain.

(((keywords, namespaces, reserved)))
As a rule, Site may recognise attributes under the namespaces of `juxt.site`, `juxt.pass`, `juxt.http`, `xtdb.api` and `xt`, but will ignore attributes in all other namespaces, including those with no namespace.

== Entities

(((entity, definition)))
The document is a _version_ of an *entity*.

(((document, identity)))
Each document has a special attribute `:xt/id` which identifies the *entity* to which the document belongs.

(((document, versioning)))
At any point in time there can, at most, be just one document for any given entity.
The example given in <<ex-cat-entity>> shows two documents representing the same entity, but at different times.

[[ex-cat-entity]]
.Two versions of the same cat.
[example]
--
A cat might be represented by the following document:

[source,clojure]
----
{:xt/id "https://example.org/cats/arya"
 :petshop/name "Arya"
 :petshop/species "cat"
 :petshop/color "black"
 :petshop/favorite-activity "playing with string"}
----

But, at a later date, the document might be updated:

[source,clojure]
----
{:xt/id "https://example.org/cats/arya"
 :petshop/name "Arya"
 :petshop/species "cat"
 :petshop/color "black"
 :petshop/favorite-activity "hunting mice"}
----
--

TIP: For more information about documents and entities, visit https://xtdb.com.

=== References

Documents can reference another entity by using the value of its `:xt/id` attribute.

References can be thought of as edges in a *graph*.

== Access control

Consider the English sentence:

"The cat sat on the mat".

The 'cat' is the *subject*.
The word 'sat' is the _verb_ (which we will call the *action*), and the 'mat' is the _object_ (which we will call the *resource*).

(((access control)))
When considering **access control**, we might rephrase the sentence as a question:

"Is the cat allowed to sit on the mat?".

If we were to ask a different question, such as:

"Is the _dog_ allowed to sit on the mat?", or

"Is the cat allowed to _wee_ on the mat?", or

"Is the cat allowed to sit on the _sofa_?",

then we may get different answers.

The point is, to satisfy most access control requirements we should consider the subject, action and resource _together_.

To avoid making access control decisions based on stale data, we need the decision logic to be where the data resides.

****
Site believes data should be protected from unauthorized access.

The greater the distance between the data and the mechanisms that protect the data, the greater the 'attack surface' that must be defended.

Placing the defences as close as possible to the data prevents a hard problem becoming a largely infeasible one.
****

[[concept-subjects]]
== Subjects

(((subject, definition)))
An individual that has access to documents in Site is represented by a *subject* document.
This is established automatically by Site when a recognised individual accesses the system.

A subject document may also contain other details, such as how and from where the user logged in, security and organisational details and other data that may be stored outside of Site.

== User identities

(((user identity, definition)))
Individuals can be recognised when they present credentials that match a *user-identity* document.
If applicable, a subject document may reference this user-identity document as part of the subject's graph, as shown in <<subject-model>>.

.The relationship between a subject and a user-identity.
[[subject-model]]
[example]
--
[plantuml,subject,svg]
....
skinparam monochrome true
@startjson
include::subject.json[]
@endjson
....
--

The only attributes of a user-identity document that are prescribed by Site are the `:juxt.site.alpha/type` and `:juxt.pass.alpha/user` attributes.

== Users

(((user, definition)))
The user-identity document does not represent the individual, only an _identity_ of an individual.
Rather, the user-identity document references another document, the *user*, that represents the recognised individual.
This is shown in <<user-identity-model>>.

.The relationship between a user-identity and a user.

[[user-identity-model]]
[example]
--
[plantuml,user-identity,svg]
....
skinparam monochrome true
@startjson
include::user-identity.json[]
@endjson
....
--

This scheme adds a little extra complexity, but allows an individual to have multiple identities, since multiple user-identity documents can reference the same user document.

The sole prescribed attribute of a user document is the `:juxt.site.alpha/type` attribute.
Other attributes can be added to the user document as required by the business or domain model.

[[concept-actions]]
== Actions

// tag::actions-definition[]
Actions govern _who_ has access to documents. Actions also govern _how_ documents are queried, created, updated and deleted.
// end::actions-definition[]

(((action, definition)))
Actions are the verbs of the domain _language_ used to tailor Site to a given business problem.

<<ex-some-actions>> illustrates some possible actions in a system:

[[ex-some-actions]]
.Some example actions
[options=header,unbreakable,cols="2,5m"]
|===
|Action|Entity id
|Login|https://example.org/actions/login
|List all products|https://example.org/actions/list-products
|Edit a product|https://example.org/actions/edit-product
|Add a customer|https://example.org/actions/add-customer
|Promote an employee|https://example.org/actions/promote-employee
|Post an article|https://example.org/actions/post-article
|Logout|https://example.org/actions/logout
|===

Naturally, actions are represented by documents.
An example document is shown in <<ex-concept-action>>.

[[ex-concept-action]]
.An example action.
[example]
--
[source,clojure]
----
include::../../test/juxt/book.clj[tag=example-action,indent=0]
----
<1> This document is marked as an action.
<2> Access control rules which govern whether this action can be used
<3> A program which computes the effects of performing this action.
--

Actions are covered in depth in <<ch-actions>>.

== Rules

An action document contains one or more *rules*.

(((rule, definition)))
A *rule* is written in terms of:

- what is known about the person or machine requesting access (the *subject*)
- what is known about the document being accessed, if applicable (the *resource*)

For example, it might be that a person's access depends on a role they have been assigned, together with the value of the resource's document classification attribute.
Or that only 'VIP' customers may access 'exclusive' special offers.

(((datalog)))
Practically speaking, a rule is written as a set of *datalog* clauses.

****
Rules can be as simple or as complex as the domain requires. The power and
expressiveness of Datalog allows for a wide range of possibilities.

When compared to other 'third-party' solutions, Site's authorization system has
two further key advantages:

* Action rules are written as graphs which are free to traverse as deep as
  necessary into the complete database of facts. Other systems must often rely
  on a small subset of facts which place limits on the flexibility of
  authorization policies.

* Action rules benefit from strong database consistency. Rules are run only
  after any pending updates to a permission have been applied. Other systems often
  cannot achieve consistency because they are implemented as services across a
  network boundary and their database of facts may be out-of-date when making
  critical authorization decisions.
****

== Permissions

(((rule head)))
Each rule is a collection of clauses, headed by the following *rule head*:

----
(allowed? subject resource permission)
----

(((permission, definition)))
A *permission* is a document which allows an action's rule to be satisfied.

If at least one permission document exists, such that all the clauses in the rule are satisfied (referencing the subject and resource, if applicable), then the action is allowed.

[TIP]
--
Think of this as an equation where a solution for the _permission_ variable must be found, in the same way as we might ask to find solutions of latexmath:[x] for the equation latexmath:[0 = x^2 - 2x + 6].
If there are no solutions which satisfy the equation, then the rule is not satisfied (and the action is denied).
--

A permission is easily deleted, and so revoking access is as straight-forward as granting access.

Permissions provide a permanent record of who had access to what, and when.

== Transactions

Actions can be given programs that will be run when the action is performed.

The program computes the effects of performing the action.
These effects may include mutations to the database.

Frequently a program will need to access the existing state of the database in order to compute its result.
So that a program does not access stale data, and thereby compute an inconstent result, the program is run as part of a transaction function.

Typically, a program will carry out input validation and transformation.
If the program completes successfully, the effects it computes are atomically applied to the state of the system.

Site provides a built-in stack-based language called *Flip* for writing these programs.

// A detailed explanation of actions, rules, permissions and the Flip language can be found in <<ch-actions>>.

[[concept-resources]]
== Resources

A resource is a document, an image, a piece of information, a data set, a collection of other resources—anything that you might want to create a hyperlink to.

A resource is identified by a Uniform Resource Identifier (URI) and represented by a document in the database.
The document's `:xt/id` is the URI.

The document contains the configuration and state of the resource, and any information required to format the resource such that it can be communicated via HTTP.

Resources are covered in depth in <<ch-resources>>.

== Authentication

Authentication is the process of establishing the *subject* of a request.

Site supports both standard HTTP Authentication and sessions created when a user provides credentials, via a login-form perhaps.

== APIs

An API is made up of a set of resources which are designed to be accessed programatically.

Resources which are part of an API can be given extra information to help supply documentation to programmers who are creating applications that accesses these API resources.
<<ch-openapi>> explains how https://www.openapis.org/[OpenAPI] documentation can be generated from a set of resources making up an API.

== Applications

An application is a piece of software that is trusted by a resource, or set of resources making up an API.
Applications are covered in depth in <<ch-applications>>.

An application can be authorized by a user in order to make APIs calls on the user's behalf.
This is the topic of <<ch-authorization-server>>.

// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// End:
