= Concepts
:step:

This chapter should give you a basic understanding of the key concepts in Site.

You should read this chapter to gain an overview before diving into the details
and practical examples in subsequent chapters.

== Documents

// (((XTDB)))
Site stores data in the form of documents.

A *document* is a set of named values called *attributes*.
An example document is shown in <<ex-cat-document>>.

[[ex-cat-document]]
.A document representing a cat.
[example]
--
[source,clojure]
----
{:petshop/name "Arya"
 :petshop/species "Cat"
 :petshop/color "black"
 :petshop/favorite-activity "playing with string"}
----
--

Names are *keywords*, which are identifiers prefixed with a colon (:).

Values can be strings, numbers, sets, collections, or nested documents.

Since nesting is recursive, a document might be a large hierarchical structure but are typically fairly small.

=== Domain independence

Site itself is independent of the domain or business context it is part of.
It is these documents that represent the domain.

A document can contain any number of attributes.
Some of these attributes are recognised by Site, and these are documented in this book.
But the rest of the attributes are entirely up to you.

Keyword namespaces are used to keep the attributes that Site recognised from conflicting with attributes that represent the domain.

As a rule, Site may recognise attributes under the namespaces of `juxt.site`, `juxt.pass`, `juxt.http`, `xtdb.api` and `xt`, but will ignore attributes in all other namespaces, including those with no namespace.

=== Entities

The document is a _version_ of an *entity*.

Each document has a special attribute `:xt/id` which identifies the *entity* to which the document belongs.

At any point in time there can, at most, be just one document for any given entity.
The example given in <<ex-cat-entity>> shows two documents representing the same entity, but at different times.

[[ex-cat-entity]]
.Two versions of the same cat.
[example]
--
A cat might be represented by the following document:

[source,clojure]
----
{:xt/id "https://example.org/cats/arya"
 :petshop/name "Arya"
 :petshop/species "cat"
 :petshop/color "black"
 :petshop/favorite-activity "playing with string"}
----

But, at a later date, the document might be updated:

[source,clojure]
----
{:xt/id "https://example.org/cats/arya"
 :petshop/name "Arya"
 :petshop/species "cat"
 :petshop/color "black"
 :petshop/favorite-activity "hunting mice"}
----
--

TIP: For more information about documents and entities, visit https://xtdb.com.

=== References

Documents can reference other entities by using a value that is equal to the `:xt/id` of the referenced entity.

References can be thought of as edges in a *graph*.

== Subjects

An individual that has access to documents in Site is represented by a *subject* document.
This is created automatically by Site when a recognised individual accesses the system.

Individuals are recognised when the credentials they present match a *user-identity* document.
A subject document will reference this user-identity document, as part of the subject's graph, as shown in <<subject-model>>.

.A subject document.
[[subject-model]]
[example]
--
[plantuml,subject,svg]
....
skinparam monochrome true
@startjson
include::subject.json[]
@endjson
....
--

The user-identity document does not represent the individual, only the identity of an individual.
Rather, the user-identity document references a further document, the *user*, that represents the recognised individual. This is shown in <<user-identity-model>>.

.A user-identity document.

[[user-identity-model]]
[example]
--
[plantuml,user-identity,svg]
....
skinparam monochrome true
@startjson
include::user-identity.json[]
@endjson
....
--

This scheme adds a little extra complexity, but allows an individual to have multiple identities, since it multiple user-identity documents can reference the same user document.

The only attributes of a user-identity document that are prescribed by Site are the `:juxt.site.alpha/type` and `:juxt.pass.alpha/user` attributes.
The sole prescribed attribute of a user document is the `:juxt.site.alpha/type` attribute.
Other attributes can be added according to the domain model.

Subjects, users, and user-identities are described in <<ch-subjects>>.

== Actions

Actions determine _who_ has access to documents and _how_ documents are queried, created, updated and deleted.

Actions are independent words that make up the _language of the system_.
You will need to define your own actions to represent the activities you want your system to perform.

Here are some example actions:

- Login
- List all products
- Edit a product
- Add a customer
- Promote an employee
- Post an article
- Logout

Naturally, actions are represented by documents.

An action document contains one or more *rules*.
A *rule* is written in terms of:

- what is known about the person or machine requesting access (the *subject*)
- what is known about the document being accessed (the *resource*)
- an explicit document that permits access to the action (the *permission*)

For example, it might be that a person's access might depend upon a role they have been assigned, and the document classification of the Resource.
Or that 'VIP' customers may access 'exclusive' special offers.

If a rule is satisfied, access to a document is granted.

Practically speaking, a rule is written as a set of *Datalog* clauses.

When an action grants the creation, modification or deletion of documents, it will also have a program that _performs_ the action.
This program might carry out validation of any inputs and return operations or effects which are applied to the state of the system.

[NOTE]
--
Technically speaking, the program associated with an action runs as part of a *transaction function* in XTDB.
If the program needs to read data from the database, this guarantees the data is up-to-date.
--

Site provides a built-in stack-based language called *Flip* for writing these programs.

<<ex-concept-action>> shows a sketch of an action document.

[[ex-concept-action]]
.An example action.
[example]
--
[source,clojure]
----
include::../../test/juxt/book.clj[tag=example-action,indent=0]
----
<1> This document is an action.
<2> Rules that govern whether this action can be used to access a document.
<3> A program which creates any effects resulting from performing the action.
--

A detailed explanation of actions, rules, permissions and the Flip language can be found in <<ch-actions>>.


////
Possibly demote this into the relevant chapter

=== Permissions

For access to be granted to a Resource, a Permission document must exist in the database.

When Rules are evaluated, these Permission documents are returned.
A Permission document represents the granting of access, whether to a specific user explicitly, or to set of users assigned a particular role, or some other relationship.

A Permission document is easily deleted, and so revoking access it as straight-forward as granting access.

Permission documents provide a permanent record of who had access to what, and when.

Rules & Permissions are described more fully in <<ch-rules-and-permissions>>.

////


== Resources

Site maps the XTDB entity onto the concept of a web resource, as defined in REST.

We can understand why XTDB entities make for good web resources, by reading the following quote from Roy Fielding's seminal paper introducing REST cite:[rest] (replacing Fielding's uses of the word 'entity for 'XTDB document).

[quote,Roy Fielding]
--
The key abstraction of information in REST is a resource. Any information that
can be named can be a resource: a document or image, a temporal service
(e.g. "today's weather in Los Angeles"), a collection of other resources, a
non-virtual object (e.g. a person), and so on. In other words, any concept that
might be the target of an author's hypertext reference must fit within the
definition of a resource. A resource is a conceptual mapping to a set of
entities, not the entity that corresponds to the mapping at any particular point
in time.

More precisely, a resource R is a temporally varying membership function
M~R~(t), which for time t maps to a set of entities, or values, which are
equivalent. The values in the set may be resource representations and/or
resource identifiers.
--

The mapping from an XTDB entity to a web resource is accomplished by the following:

* Each XTDB entity's `:xt/id` attribute is set to a URL (string), identifying the resource.
* Representation metadata is encoded into document attributes.

<<ex-cat-resource>> shows a document that (currently) has a single representation, of HTML.

[[ex-cat-resource]]
.A cat, viewable in a web browser.
[example]
--
[source,clojure]
----
{:xt/id "https://example.org/cats/arya"
 :juxt.http.alpha/content-type "text/html;charset=utf-8" <1>
 :petshop/name "Arya"
 :petshop/species "cat"
 :petshop/color "black"
 :petshop/favorite-activity "playing with string"}
----
<1> This attribute declares that the resource is representable as HTML.
--

Site provides access to these resources via the HTTP protocol cite:[rfc7231], including support for:

* content-negotiation
* method semantics
* response codes
* conditional requests
* range requests
* authentication

Resources are covered in depth in <<ch-resources>>.

// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// End:
