= Form-Based Authentication
:toc: left
:experimental:

== Introduction

In this chapter we'll create a login form that will allow a user access to a
protected resource.

We'll need to create the following resources:

. A document at `+https://site.test/protected-by-session-scope/document.html+`
which requires the User can perform the Action
`+https://site.test/actions/get-protected-resource+`. We'll called this the
_protected document_. This is explained in <<create-resource-protected-by-session-scope>>.

. A Permission to allow Alice to access this protected document. This is added
in <<grant-permission-to-resource-protected-by-session-scope>>.

. A Session Scope that redirects unauthenticated requests when necessary. This is
added in <<create-session-scope>>.

. A login form that will be shown to the User, allowing them to
authenticate. We'll also want this resource to handle the POST request that
occurs when a User submits the login formfootnote:[Keeping the resource the same is convenient because it means we don't have to worry about the value of the form's `action` attribute.]. This is created in
<<create-login-resource>>.

. An Action that can be used when the POST request is received. This Action will
attempt to find a User Identity that matches some received credentials. If one
if found, the Action will create a Subject in the database.

. A User Identity for Alice, including a username/password pair, that Alice can use
to authenticate using the form. This is added in <<session-scope-add-user-identity>>.

<<session-scope-flow>> shows the interaction between the components.

.How session-based authentication works in Site
[[session-scope-flow]]
[plantuml,session-scope-flow,svg]
....
skinparam monochrome true
autonumber

actor Alice as user
participant browser

participant "/…/document.html" as document
participant "/login.html" as loginform
participant "/login" as loginhandler
participant Pass as pass
participant "login procedure" as loginproc
database XTDB

user -> browser: Click href\nto document
browser -> document: GET
document -> pass: Check permission
document <- pass: Denied
document -> pass: Lookup session scopes
document <- pass: Session scope
browser <- document: 302 Found
browser -> loginform: GET
' loginform -> pass: Create session
' pass -> XTDB: Create session entity
browser <- loginform: 200 OK\nwith HTML form in body
user -> browser: Enter credentials,\nsubmit
browser -> loginhandler: POST
loginhandler -> pass: Check permission\nto perform action
loginhandler <- pass: Approved
loginhandler -> pass: Perform login action
pass -> loginproc: Submit\ntransaction\nfunction
loginproc -> XTDB: Find identity\nwith credentials
loginproc <- XTDB: Matched identity
loginproc -> XTDB: Create subject, session
pass <- loginproc: Get session token
loginhandler <- pass: Set-Cookie for session
browser <- loginhandler: 302 Found with Set-Cookie
browser -> document: GET
document -> pass: Check permission
document <- pass: Approved
browser <- document: 200 OK
user <- browser: document
....

In <<session-scope-flow>>, the following steps are illustrated:

. Alice enters a URI (or clicks on a link) to browse a document.

. The browser sends a GET request to the protected document:
`+https://site.test/protected-by-session-scope/document.html+`.

. The operation is associated with the Action
`+https://site.test/actions/get-protected-resource+` and a check is made for a
permission to perform this Action.

. No permission is matched, the request is denied.

. In denying the request, a session scope is looked up.

. One is found and returned, associated with the URI of a login form.

. A `302 Found` response is send containing a `Location` header of the URI of
the login form.

. The browser redirects to the URI contained in the `Location` header of the
previous response (in this case, `/login.html`).

. The URI locates a resource which returns the HTML of a login form, with an
`action` attribute containing the URI of a resource that will handle the
credentials (in this case, `/login`).

. Alice enters her credentials and clicks btn:[Submit].

. The browser makes a POST request to the resource identified by the form's
`action` attribute, with a body that contains the credentials.

. The Action associated with the POST method on this resource is looked up
(`+https://site.test/actions/login+`). The system searches for a permission to
perform this Action.

. Since the login form is intended as a public resource, a permission is found
to exist and the request is allowed to proceed.

. The `+https://site.test/actions/login+` Action is performed.

. All actions are run as transaction functions in XTDB in order to guarantee
database consistency and preserve a deterministic log of serialized
transactions. The `+https://site.test/actions/login+` Action contains a
procedural 'program' which is run inside the transaction function.

. One of the first steps of the procedure is to find a User Identity that
matches the credentials received in the request body.

. A matching User Identity exists for Alice which is returned, otherwise the
procedure throws an error and the transaction aborts.

. (create subject, session, session-token)

. (associate session token in log entry)

. (set-cookie corresponding to session)

. (302 found)

. (get original resource)

. (check permission)

. (approved)

. (200 OK)

. (document)

[[create-resource-protected-by-session-scope]]
== Create the protected resource

.Creating the protected resource
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=create-resource-protected-by-session-scope!,indent=0]
----
====

[[grant-permission-to-resource-protected-by-session-scope]]
== Permit Alice to access the protected resource

.Permitting Alice to access the protected resource
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=grant-permission-to-resource-protected-by-session-scope!,indent=0]
----
====

[[create-session-scope]]
== Create the session scope

.Creating the session scope
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=create-session-scope!,indent=0]
----
====

[[create-login-resource]]
== Create the login resource

.Creating the login resource
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=create-login-resource!,indent=0]
----
====

[[create-login-action]]
== Create the login action

.Creating the login action
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=create-action-login!,indent=0]
----
====

.Granting permission for all to perform the login action
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=permit-action-login!,indent=0]
----
====

// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// End:
