= Understanding the Bootstrap
:toc: left
:experimental:

(((bootstrapping)))
In this chapter we will explain the bootstrap process initiated in <<bootstrap>>.

== The primordial entities

(((primordial entities)))
Before we can start to create and perform actions, we must start by installing four _primordial_ entities:

* A *subject* that will only be used to bootstrap the system to a point where we have real users (<<bootstrap-install-system-subject>>).

* An *action* that allows the creation of other actions (<<bootstrap-install-create-action>>).

* A *permission* to allow the *subject* (created in <<bootstrap-install-repl-subject>>) to call the action (created in <<bootstrap-install-system-permissions>>).

* A *transaction function* that we can use to _perform_ an action (<<bootstrap-install-transaction-function>>).

[[bootstrap-install-system-subject]]
=== The system subject

(((system subject)))
The system subject is created to perform certain actions that are not authorized by general users of the system.
It is primarily used for bootstrapping the system and should not be used afterwards.
It is similar to the Unix `root` user.

[source,clojure]
----
include::../../test/juxt/book.clj[tag=install-system-subject!,indent=0]
----

[[bootstrap-install-create-action]]
=== The creator action

(((create-action)))
Next we install a single action that which allows us to create all other actions.

Let's examine the document that represents this action:

.The create-action action
[source,clojure]
----
include::../../test/juxt/book.clj[tag=install-create-action!,indent=0]
----
<1> This rule allows our system subject to call this action, if an explicit permission exists.

<2> This Malli schema restricts the URIs of new Actions. Again, this should be
modified if necessary to correspond to a different base URI.

<3> This sets the `:juxt.site.alpha/type` attribute so that the document is treated as an action.

[[bootstrap-install-system-permissions]]
=== The system permissions

The system subject cannot call the `create-action` action without being granted permission.

The permission document

.The initial system permissions
[source,clojure]
----
include::../../test/juxt/book.clj[tag=install-system-permissions!,indent=0]
----
<1> This attribute tells Site this is a permission document
<2> This is the set of actions which the permission allows
<3> This purpose attribute must be included in every permission but is set to nil in most cases
<4> This attribute is what satisfies the rule in `create-action`

[[bootstrap-install-transaction-function]]
=== The action transaction function

(((do-action, transaction function, registration)))
When actions are performed which modify the database, they run in a transaction function.

XTDB requires that we register this transaction function before we call it.

<<ex-do-action-transaction-function>> shows the document that represents this transaction function in the database.

[[ex-do-action-transaction-function]]
.The do-action transaction function
[example]
--
[source,clojure]
----
{:xt/id "https://site.test/_site/do-action"
 :xt/fn (fn [xt-ctx ctx & args]
          (juxt.pass.alpha.authorization/do-action* xt-ctx ctx args))}
----
--

NOTE: It is not necessary to understand this step in detail, only that it is required.


// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// End:
