= Protecting Resources
:toc: left

[[publishing-protected-resources]]
== Creating a protected resource

Now let's publish an immutable protected resource which can only be seen by an
authenticated user.

We'll need an action to publish a protected resource.


.Creating and accessing a protected resource
====

Again, let's complete the following steps:

[source,clojure]
----
include::../../test/juxt/book.clj[tag=create-action-put-immutable-protected-resource!,indent=0]
----

[IMPORTANT]
--
Do it
--

We'll grant this permission to our REPL user.

[source,clojure]
----
include::../../test/juxt/book.clj[tag=grant-permission-to-put-immutable-protected-resource!,indent=0]
----

[IMPORTANT]
--
Do it
--

Now we'll create the action that is used to get a protected resource. The rules
mandate that a permission has been granted on a specific resource and the
subject is not nil.

[source,clojure]
.Creating the `get-protected-resource` action
----
include::../../test/juxt/book.clj[tag=create-action-get-protected-resource,indent=0]
----

[IMPORTANT]
--
Do it
--

The `get-protected-resource` action's rules state that a single 'global'
permission (referencing the action) is sufficient for _any_ authenticated
end-user (subject) to access the action.

But we must rememeber to create that single global permission:

[source,clojure]
.Creating the global grant on `get-protected-resource` to authenticated users
----
include::../../test/juxt/book.clj[tag=grant-permission-to-get-protected-resource!,indent=0]
----

[IMPORTANT]
--
Do it
--

Now to create a protected resource.

[source,clojure]
----
include::../../test/juxt/book.clj[tag=create-immutable-protected-resource!,indent=0]
----

[IMPORTANT]
--
Do it
--

Let's try to access the protected resource.

----
curl -i https://site.test/protected.html
----

We should get a response with a 401 status. We're not authorized to access this
resource.

----
HTTP/1.1 401 Unauthorized
Server: nginx/1.20.2
Date: Sat, 09 Apr 2022 08:12:40 GMT
Content-Type: text/plain;charset=utf-8
Content-Length: 14
Connection: keep-alive
site-request-id: https://site.test/_site/requests/980cf294f4ab87688c65581d
permissions-policy: interest-cohort=()

Unauthorized
----
====
