= Resources
:toc: left

Resources in Site are web resources, as per https://httpwg.org/specs/rfc7231.html#resources[RFC 7231].

Resourse are identified by a URI. When resources are stored in XT, the
resource's URI is the `:xt/id` attribute.

A web resource is a series of states across time, just like an XT entity.

In this section we'll create a basic plain-text public resource containing the
classic greeting.

== Anatomy of a Site resource

In Site, every XT document represents a web resource. This means that the terms
resource and document are somewhat synonymous in Site documentation.

In the same way every web resource has a Uniform Resource Identitier (URI),
every document in the XTDB database has an XT (`:xt/id`) identifier.

In this way, exposing data to the web is trivial. There is convoluted logic or
mappings, it's a simply one-to-one correspondence. All Site does is provide the
protocol layer to handle HTTP requests.

Site uses the request URI to lookup the corresponding XT document, and uses
certain known attributes of the document to determine the web resource's
configuration and state. This mapping is illustrated in
<<http-protocol-mappings>>. The values of these attributes determine the
corresponding status, headers and body of the protocol response.

[NOTE]
--
Beyond the `:xt/id` id attribute, the attribute keywords that are
recognised by Site as having special significance are qualified by namespaces
reserved by Site. These always start with `juxt` and there are a handful of
namespaces which are used, such as `juxt.http`, `juxt.site` and
`juxt.pass`.

It's important to understand that these XT documents are _your_ documents, with
attributes you choose from _your_ domain. The documents are merely augmented
with additional non-conflicting attributes recognised by Site.
--

.HTTP protocol mappings to XT document attributes
[[http-protocol-mappings]]
|===
|Web|XT

|URI|`:xt/id`
|Methods|`:juxt.http.alpha/methods`
|Representations|`:juxt.site.alpha/variant-of`
|Body|`:juxt.http.alpha/body`, `:juxt.http.alpha/content`
|Content Type|`:juxt.http.alpha/content-type`
|Content Language|`:juxt.http.alpha/content-language`
|Content Location|`:juxt.http.alpha/content-location`
|Content Encoding|`:juxt.http.alpha/content-encoding`
|Last-Modified|`:juxt.http.alpha/last-modified`
|ETag|`:juxt.http.alpha/etag`
|Content Length|`:juxt.http.alpha/content-length`
|Trailer|`:juxt.http.alpha/trailer`
|Transfer-Encoding|`:juxt.http.alpha/transfer-encoding`
|Vary|`:juxt.http.alpha/vary`
|OPTIONS|`:juxt.http.alpha/options`
|===

In fact, you can think of XT as the a file-system to a static web-server. But
rather than encoding web metadata in filename conventions and convoluted
configuration, a web resource (its state, configuration and metadata) is stored
in a database, where it can be more easily managed, queried and updated. _A
database is simply a better place for this data than a file-system._ In the same
way you'd run an Apache web server over a file-system to publish to the web, you
run Site over an XTDB database.

== Publishing a public resource

Before we can create the resource, we need to define an action that lets us do so.

In many organisations, publishing information to the public web may well be a
restricted operation so <<create-action-put-immutable-public-resource>> shows
how to do so.

.Creating a public resource
[[ex-create-public-resource]]
====
We'll do the following steps:

. Create an action
. Grant permission to invoke the action
. Call the action

The action contains both the validation rules to ensure that only GET, HEAD and
OPTIONS methods are allowed, and that these map onto the correct actions.

[source,clojure]
----
include::../../dev/demo.clj[tag=create-action-put-immutable-public-resource!,indent=0]
----
<1> We'll put this action in the `write:resource` scope
<2> We add (or override) the HTTP methods allowed on this resource. Each entry is a mapping from an allowed method to a set of actions. This restricts the search for permissions to a set of actions. The fact that we don't specify any methods such as PUT, POST or DELETE that will change the resource is the reason we've named this action as creating an immutable public resource.
<3> This rule ensures this action must be specifically granted to someone.
====

[IMPORTANT]
--
Copy the code in the <<ex-create-public-resource>>, paste it into a REPL and evaluate.
--

====
Now we must grant permission for our REPL user to use this action:

[source,clojure]
----
include::../../dev/demo.clj[tag=grant-permission-to-invoke-action-put-immutable-public-resource!,indent=0]
----

[IMPORTANT]
--
Do it!
--

When Site receives a web request for a resource it will look for a `juxt.site.alpha/methods`
entry which indicates which action or actions should be used when seeking
permission.

In effect, this allows the resource to indicate which rules are to be used
in determining whether a user can access the resource.

A `GET` request on our Hello World resource implies will correspond to the
`https://site.test/actions/get-public-resource` action, so we'll need to create
that now.

[source,clojure]
----
include::../../dev/demo.clj[tag=create-action-get-public-resource!,indent=0]
----
<1> We use a more appropriate scope that better reflects this action.
<2> This is a very weak rule that matches a particular permission.

[IMPORTANT]
--
Do it
--

A permission document _must_ exist for every case.
The rule of the `http://site.test/actions/get-public-resource` requires a specific permission to exist, so we need to create that now.

[source,clojure]
----
include::../../dev/demo.clj[tag=grant-permission-to-invoke-get-public-resource!,indent=0]
----

IMPORTANT: Do it!

====

[[hello-world]]
=== Hello World!

To demonstrate our new `put-immutable-public-resource` action, let's publish a
resource that will print `Hello World!` on a web page.

.Creating a simple public 'Hello World' resource
[[hello-world-example]]
====
[source,clojure]
----
include::../../dev/demo.clj[tag=create-hello-world-resource!,indent=0]
----

[IMPORTANT]
--
Do it
--

Now we can test access with `curl`:

----
curl -i https://site.test/hello
----

[IMPORTANT]
--
Do it
--

You should get a `200` response similar to this:

----
HTTP/1.1 200 OK
Server: nginx/1.20.2
Date: Mon, 28 Mar 2022 00:15:15 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
site-request-id: https://site.test/_site/requests/f8a1a799c72e28ec2409c1d5
permissions-policy: interest-cohort=()

Hello World!
----
====
