= Resources
:toc: left

Resources in Site are web resources, as per
https://httpwg.org/specs/rfc7231.html#resources[RFC 7231].

Resourse are identified by a URI. When resources are stored in XT, the
resource's URI is the `:xt/id` attribute.

A web resource is a series of states across time, just like an XT entity.

In this section we'll create a basic plain-text public resource containing the
classic greeting.

== Anatomy of a Site resource

In Site, every XT document represents a web resource. This means that the terms
resource and document are somewhat synonymous in Site documentation.

In the same way every web resource has a Uniform Resource Identitier (URI),
every document in the XTDB database has an XT (`:xt/id`) identifier.

In this way, exposing data to the web is trivial. There is convoluted logic or
mappings, it's a simply one-to-one correspondence. All Site does is provide the
protocol layer to handle HTTP requests.

Site uses the request URI to lookup the corresponding XT document, and uses
certain known attributes of the document to determine the web resource's
configuration and state. This mapping is illustrated in
<<http-protocol-mappings>>. The values of these attributes determine the
corresponding status, headers and body of the protocol response.

[NOTE]
--
Beyond the `:xt/id` id attribute, the attribute keywords that are
recognised by Site as having special significance are qualified by namespaces
reserved by Site. These always start with `juxt` and there are a handful of
namespaces which are used, such as `juxt.http`, `juxt.site` and
`juxt.pass`.

It's important to understand that these XT documents are _your_ documents, with
attributes you choose from _your_ domain. The documents are merely augmented
with additional non-conflicting attributes recognised by Site.
--

.HTTP protocol mappings to XT document attributes
[[http-protocol-mappings]]
|===
|Web|XT

|URI|`:xt/id`
|Methods|`:juxt.http.alpha/methods`
|Representations|`:juxt.site.alpha/variant-of`
|Body|`:juxt.http.alpha/body`, `:juxt.http.alpha/content`
|Content Type|`:juxt.http.alpha/content-type`
|Content Language|`:juxt.http.alpha/content-language`
|Content Location|`:juxt.http.alpha/content-location`
|Content Encoding|`:juxt.http.alpha/content-encoding`
|Last-Modified|`:juxt.http.alpha/last-modified`
|ETag|`:juxt.http.alpha/etag`
|Content Length|`:juxt.http.alpha/content-length`
|Trailer|`:juxt.http.alpha/trailer`
|Transfer-Encoding|`:juxt.http.alpha/transfer-encoding`
|Vary|`:juxt.http.alpha/vary`
|OPTIONS|`:juxt.http.alpha/options`
|===

XT is to Site what a file-system is to a static web-server, such as Apache.

Apache encodes web metadata in the filename. For example, the filename
`foo.en.html.gz` encodes the language (English), media-type (HTML) and encoding
(gzip) into the filename.

Site takes a different approach, using the database to encode web metadata where
it can be more easily managed, queried and updated.

_A database is simply a better place for web resource metadata than a
file-system._

For the remainder of this section we'll discuss a selection of these special
Site attributes.

=== Methods

(((web methods)))
The `:juxt.http.alpha/methods` attribute value is a map of entries, one for each
web method.

The value of each entry is another map, which contains configuration data for
the web method.

(((status, 405)))
Only methods included in this map are allowed by the resource. If not specified, a request method will be met with a `405 No Such Method` response.

(((Allow header)))
These methods are also used to generate the `Allow` header in web responses,
where applicable.

For instance, the actions that are used for each method are listed in the
`juxt.pass.alpha/actions` entry.

When Site receives a web request for a resource it will look for a
`juxt.site.alpha/methods` entry which indicates which action or actions should
be used when seeking permission.

In effect, this allows the resource to indicate which rules are to be used in
determining whether a user can access the resource.

<<ex-http-methods>> shows an example of a `:juxt.http.alpha/methods` entry.

[[ex-http-methods]]
.A `:juxt.http.alpha/methods` entry
====
[source,clojure]
----
{:juxt.http.alpha/methods
  {:get
    {:juxt.pass.alpha/actions
      #{"https://site.test/actions/get-shopping-list"}}
   :post
    {:juxt.pass.alpha/actions
      #{"https://site.test/actions/post-shopping-list-item"}}}}
----
====

== Publishing a public resource

Let's publish a resource to Site that everyone can see.

NOTE: In many organisations, publishing information to the public web may well be
a restricted operation, so the action might be restricted to authorized users.

We'll need to perform these steps:

. Create an action for accessing a public resource
. Grant the permission for anyone to perform this action
. Create an action for creating a public resource
. Grant the permission for the REPL user to perform this action

Let's start with the first action, shown in <<ex-get-public-resource>>.

.Accessing a public resource
[[ex-get-public-resource]]
====
[source,clojure]
----
include::../../test/juxt/demo.clj[tag=create-action-get-public-resource!,indent=0]
----
<1> We use a more appropriate scope that better reflects this action.
<2> This is a very weak rule that matches a particular permission.
====

[IMPORTANT]
--
Copy the code in <<ex-get-public-resource>>, paste it into a REPL and evaluate.
--

A Permission _must_ exist for an Action to be allowed.

Note in <<ex-get-public-resource>> the Rules referenced the existence of a Permission, `https://site.test/permissions/public-resources-to-all`. This is created in <<ex-permit-get-public-resource>>.

.Creating the permission for everyone to access public resources
[[ex-permit-get-public-resource]]
====
[source,clojure]
----
include::../../test/juxt/demo.clj[tag=grant-permission-to-invoke-get-public-resource!,indent=0]
----

====

[IMPORTANT]
--
Copy the code in <<ex-permit-get-public-resource>>, paste it into a REPL and evaluate.
--

Now we create the Action that can be used to create public resources. The Action
ensures that the resources it creates set the correct methods (GET, HEAD and
OPTIONS) and the corresponding Actions those methods map onto.

For instance, a `GET` request on resources created with this Action would
correspond to the `https://site.test/actions/get-public-resource` action we
created in <<ex-get-public-resource>>.

<<ex-create-public-resource>> demonstrates the creation of our Action at the
REPL.

.Creating the Action to create a public resource
[[ex-create-action-to-create-public-resource]]
====
[source,clojure]
----
include::../../test/juxt/demo.clj[tag=create-action-put-immutable-public-resource!,indent=0]
----
<1> We'll put this action in the `write:resource` scope
<2> We add (or override) the HTTP methods allowed on this resource. Each entry is a mapping from an allowed method to a set of actions. This restricts the search for permissions to a set of actions. The fact that we don't specify any methods such as PUT, POST or DELETE that will change the resource is the reason we've named this action as creating an immutable public resource.
<3> This rule ensures this action must be specifically granted to someone.
====

[IMPORTANT]
--
Copy the code in <<ex-create-public-resource>>, paste it into a REPL and evaluate.
--

We mustn't forget to grant permission for our REPL user to perform this
action. This is shown in <<ex-permit-create-public-resource>>.

.Granting permission to create a public resource
[[ex-permit-create-public-resource]]
====
In this example, we allow anyone with the role of `Administrator` to perform the action of creating public resources.

[source,clojure]
----
include::../../test/juxt/demo.clj[tag=grant-permission-to-invoke-action-put-immutable-public-resource!,indent=0]
----
====

[IMPORTANT]
--
Copy the code above, paste it into a REPL and evaluate.
--


[[hello-world]]
=== Hello World!

Finally we can demonstrate that the action we created in <<ex-create-action-to-create-public-resource>>.

To demonstrate our new `put-immutable-public-resource` action, let's publish a
resource that will print `Hello World!` on a web page.

.Creating a simple public 'Hello World' resource
[[hello-world-example]]
====
[source,clojure]
----
include::../../test/juxt/demo.clj[tag=create-hello-world-resource!,indent=0]
----
====

[IMPORTANT]
--
Copy the code in <<hello-world-example>> above, paste it into a REPL and evaluate.
--

Now we can test access with `curl`:

====
----
curl -i https://site.test/hello
----

You should get a `200` response similar to this:

----
HTTP/1.1 200 OK
Server: nginx/1.20.2
Date: Mon, 28 Mar 2022 00:15:15 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
site-request-id: https://site.test/_site/requests/f8a1a799c72e28ec2409c1d5
permissions-policy: interest-cohort=()

Hello World!
----
====
