= Site
Malcolm Sparks <mal@juxt.pro>
v1.0, 2022-06-21
:doctype: book
:toc: left
:toclevels: 2
:sectnums:
:sectnumlevels: 4
:xrefstyle: short
:stem:

[colophon]
--
First Edition.

Copyright © 2022, JUXT LTD. All Rights Reserved.

Published by JUXT Text.

This book is written with Asciidoctor.

Available in PDF, ebook and HTML editions.

HTML edition available at https://text.juxt.site/site-book.html

--

toc::[]

include::Introduction.adoc[leveloffset=+1]

=== Values & Principles

include::Values.adoc[leveloffset=+3]

include::Principles.adoc[leveloffset=+3]



include::Concepts.adoc[leveloffset=+1]

include::Installation.adoc[leveloffset=+1]

////
= Preliminaries

If you're in a hurry, or want to get started quickly with Site, you should skip
these chapters and move onto <<ch-resources>>.

However, in keeping with our value of <<understanding,Understanding>>, we
recommended that you invest time in building up both your working and conceptual
knowledge of Site. These chapters will help to build up your knowledge of Site
'from scratch'. If you've chosen this course, welcome to the slow track!
////

= Subjects, Actions & Resources

Consider the English sentence: "The cat sat on the mat".

The 'cat' is the *subject*.
The word 'sat' is the _verb_ (which we will call the *action*), and the 'mat' is the _object_ (which we will call the *resource*).

When considering **access control**, we might rephrase the sentence as a question: "Is the cat allowed to sit on the mat?".

If we were to ask a different question, such as

* "Is the dog allowed to sit on the mat?", or
* "Is the cat allowed to wee on the mat?", or
* "Is the cat allowed to sit on the sofa?",

then we may get different answers.

The point is, we cannot effectively control access to resources without considering the subject, action and resource *together*.


[[ch-subjects]]
include::Subjects.adoc[leveloffset=+1]
[[ch-creating-users]]
include::UsersRevisited.adoc[leveloffset=+2]

[[ch-actions]]
include::Actions.adoc[leveloffset=+1]

[[ch-resources]]
include::Resources.adoc[leveloffset=+1]

include::Representations.adoc[leveloffset=+2]

= Authentication

(((authentication, definition)))
Authentication is the process by which a user is identified.

(((access control)))
In Site, Actions are integrated with authorization rules, providing a rich access control
layer between users and data.

(((Subject)))
Most authorization rules refer to the Subject of the request. To identify the
Subject, we need to authenticate each request.

Site supports two types of user authentication:

(((authentication,HTTP))) *HTTP Authentication*, which introduces the concept of
_protection spaces_, specified in https://www.rfc-editor.org/rfc/rfc7235[RFC
7235], is described in <<ch-http-authentication>>. An example of HTTP
Authentication is the 'Basic' authentication scheme, which is covered in
<<ch-basic-authentication>>.

(((authentication,session-based))) *Session-based Authentication*, which we
describe in <<ch-session-authentication>>, opens up numerous additional options
for authentication. One such option is authenticating via an HTML form, which is
covered in <<ch-form-based-authentication>>. Another is with the OpenID Connect
protocol, which is covered in <<ch-openid>> with a worked example.

include::ProtectingResources.adoc[leveloffset=+1]

[[ch-http-authentication]]
include::HttpAuthentication.adoc[leveloffset=+1]

[[ch-basic-authentication]]
include::BasicAuthentication.adoc[leveloffset=+1]

[[ch-sessions]]
include::Sessions.adoc[leveloffset=+1]

[[ch-form-based-authentication]]
include::FormBasedAuthentication.adoc[leveloffset=+1]

[[ch-openid]]
include::OpenIdAuthentication.adoc[leveloffset=+1]

= Applications and APIs


First, in <<ch-applications>>, we introduce Applications and create the required
Actions.

We start by configuring our Authorization Server in <<ch-authorization-server>>.

Then, in <<ch-first-application>>, we create an example Application.

[[ch-applications]]
include::Applications.adoc[leveloffset=+1]

[[ch-authorization-server]]
include::AuthorizationServer.adoc[leveloffset=+1]

[[ch-first-application]]
include::FirstApplication.adoc[leveloffset=+1]

[[ch-openapi]]
include::OpenAPI.adoc[leveloffset=+1]

[[ch-graphql]]
include::GraphQL.adoc[leveloffset=+1]

= Going further

include::ErrorResources.adoc[leveloffset=+1]

// Create an action to list-identities
// Create a resource at /users that is attached to list-identities

// include::APIs.adoc[leveloffset=+1]

// [[authorization]]
// include::Authorization.adoc[leveloffset=+1]

include::NextSteps.adoc[leveloffset=+1]

include::AppDevelopment.adoc[leveloffset=+1]

= Websites with Site

include::Templates.adoc[leveloffset=+1]

include::Glossary.adoc[]

[bibliography]
= References

bibliography::[]

[index]
== Index
