= Users Revisited
:toc: left
:experimental:

In <<ch-users>> we put Documents directly the database to represent an initial User.

Actions can't be invoked without a User, yet Actions, but Actions are required
to create Users. We had a chicken-and-egg situation that we resolved by directly
inserting the first user by hand.

However, now that we have built the capability to create Actions and
Permissions, we can build the Actions to create new Users, Identities and
Subjects. That's the subject of this chapter.

== Create an action to create a user

[[ex-create-action-put-user]]
.Creating an action to put a user
====
[source,clojure]
----
include::../../test/juxt/demo.clj[tag=create-action-put-user!,indent=0]
----
====

[IMPORTANT]
--
Copy the code in <<ex-create-action-put-user>>, paste it into a REPL and evaluate.
--

== Create an Action to create a User Identity

An Action to create a user should

[[ex-create-action-put-user-identity]]
.Creating an Action to put a User Identity
====
[source,clojure]
----
include::../../test/juxt/demo.clj[tag=create-action-put-identity!,indent=0]
----

[source,clojure]
----
include::../../test/juxt/demo.clj[tag=grant-permission-to-invoke-action-put-identity!,indent=0]
----
====

[IMPORTANT]
--
Copy the code in <<ex-create-action-put-identity>>, paste it into a REPL and evaluate.
--

== Create an Action to create an Subject

[[ex-create-action-put-subject]]
.Creating an action to put a subject
====
[source,clojure]
----
include::../../test/juxt/demo.clj[tag=create-action-put-subject!,indent=0]
----

[source,clojure]
----
include::../../test/juxt/demo.clj[tag=grant-permission-to-invoke-action-put-subject!,indent=0]
----
====

[IMPORTANT]
--
Copy the code in <<ex-create-action-put-subject>>, paste it into a REPL and evaluate.
--
