= Site Installation

This guide explains the process of setting up a site-server on a remote host.

We assume you have access to the host (we'll call it `host`) and that a user
exists to run the site-server (we'll call it `site`).

== Installation

----
$ ssh -A site@host
----

Clone the site repo

----
site$ git clone https://github.com/juxt/site
----

Logout and back in again

----
$ ssh site@host
----

== Configuration

----
site$ mkdir -p $HOME/.config/site
site$ cp $HOME/site/doc/config.edn $HOME/.config/site/config.edn
----

Copy over the systemd script (and edit as appropriate)

----
site$ sudo cp $HOME/site/etc/systemd/site.service /etc/systemd/system/site.service
----

== Execution

Start site

----
site$ sudo systemctl start site
----

Monitor initial start up for errors

----
site$ sudo journalctl -xefu site
----

Ensure site is started after a reboot of the host

----
site$ sudo systemctl enable site
----

== Bootstrap

----
site$ curl localhost 50505

Site by JUXT. Copyright (c) 2021, JUXT LTD.

[ ]  Site API not installed.  Enter (put-site-api!) to fix this.
[ ]  Authentication resources not installed.  Enter (put-auth-resources!) to fix this.
[ ]  Role of superuser not yet created. Enter (put-superuser-role!) to fix this.
[ ]  No superusers exist. Enter (put-superuser! <username> <password> <fullname>) to fix this.

juxt.site.alpha.repl=>
----

As prompted, create the various resources to populate the server. Now that you
have a superuser account, you can continue to populate the server remotely.

For example:

----
juxt.site.alpha.repl=> (put-superuser-role!)
----


== Setup

The site tool is now ready to use. You can add resources using the site tool depending on what you need.

----
$ site get-token -u <superuser>
----

Here are some examples of commands you could try:

----
$ site put-swagger-ui
----

To install some CSS and variants

----
$ site put-asset --file style/target/styles.css --type text/css --path /css/styles.css
$ site put-asset --file style/target/styles.css.gz --type text/css --encoding gzip --path /css/styles.css.gz
$ site put-variant -r https://home.juxt.site/css/styles.css -v https://home.juxt.site/css/styles.css.gz
$ site put-asset --file style/target/styles.css.br --type text/css --encoding br --path /css/styles.css.br
$ site put-variant -r https://home.juxt.site/css/styles.css -v https://home.juxt.site/css/styles.css.br
----

Login resources

----
$ site put-asset --file assets/favicon.ico --type image/x-icon --path /favicon.ico
$ site put-asset --file assets/login.html --type 'text/html;charset=utf-8' --path /login.html
$ site put-asset --file assets/live.js --type 'application/javascript' --path /js/live.js
$ site put-asset --file assets/juxt-logo-on-black.svg --type 'image/svg+xml' --path /juxt-logo-on-black.svg
$ site put-asset --file assets/juxt-logo-on-white.svg --type 'image/svg+xml' --path /juxt-logo-on-white.svg
$ site put-rule -n login-form -r rules/login-form-rule.json
----

where `rules/login-form-rule.json` might be:

[source,json]
----
{"type": "Rule",
 "target": "[(or [request :ring.request/path \"/login.html\"] [request :ring.request/path \"/juxt-logo-on-black.svg\"] [request :ring.request/path \"/juxt-logo-on-white.svg\"] [request :ring.request/path \"/css/styles.css\"] [request :ring.request/path \"/favicon.ico\"])]",
 "effect": "juxt.pass.alpha/allow"}
----

Add a redirect from / to a login page with a query parameters

----
site put-redirect -r / -l /login.html
----
