#!/bin/bash

# GraphiQL console
site -s put-asset --file index.html --type "text/html;charset=utf8" --path /graphiql/index.html

# Set up /graphql to be a schema end-point where we can PUT schemas
site -s post-resources --file resources.edn

# Put the schema
site -s put-asset --file schema.graphql --type application/graphql --path /graphql

site -s post --data "{ holidays { id user { id username name email } startDate endDate description } }" --path "/graphql" --type "application/graphql"
