.PHONY: all install

all:	install

install:
	@site put-static-site -d build -p _insite
#	@site put-template --dialect "selmer" --file request-template.html --type 'text/html;charset=utf-8' --path /_site/templates/request.html
